apiVersion: v1
kind: Service
metadata:
  name: length-service
  labels:
    app: length-service
spec:
  selector:
    app: length-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP
