apiVersion: v1
kind: Service
metadata:
  name: hash-service
  labels:
    app: hash-service
spec:
  selector:
    app: hash-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
